name: flutter_api_sample
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Riverpod + hooks
  hooks_riverpod: ^2.0.0-dev.9
  flutter_hooks: ^0.18.5+1

  # Streams
  rxdart: ^0.27.5

  # Http client
  dio: ^4.0.6

  # Code generator
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  flutter_gen: ^4.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  freezed: ^2.1.0+1
  build_runner: ^2.2.0
  flutter_gen_runner: ^4.1.6
  json_serializable: ^6.3.1

flutter:
  uses-material-design: true
